title: httpoxy
email: contact@httpoxy.org
description: >
  httpoxy is a vulnerability in PHP and CGI web applications that allows remote attackers to proxy requests
baseurl: ""
url: "https://httpoxy.org"

markdown: kramdown

exclude:
  - ci/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-assets
  - bootstrap
